# Generated by Django 4.0.1 on 2022-01-28 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('latitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('photo_owner_id', models.IntegerField(blank=True, null=True)),
                ('collection_id', models.IntegerField(blank=True, null=True)),
                ('current_view_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='View_ids_of_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conjunctive', models.BooleanField(blank=True, null=True)),
                ('startLatitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('startLongitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('endLatitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('endLongitude', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('view_owner_id', models.IntegerField(blank=True, null=True)),
                ('collection_id', models.IntegerField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, to='photos.Photo')),
                ('shared_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='photos.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='view_id',
            field=models.ManyToManyField(blank=True, to='photos.View_ids_of_photo'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('collection_owner_id', models.IntegerField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, to='photos.Photo')),
                ('shared_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, to='photos.View')),
            ],
        ),
    ]
